name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd /opt/apps/sample_backend

            git pull origin main

            source venv/bin/activate

            pip install -r requirements.txt

            sudo systemctl restart backend

            echo "Deployment completed successfully"